name: Build
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: msbuild src/CurlDebuggerVisualizer/CurlDebuggerVisualizer.csproj /p:Configuration=Release
      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: CurlDebuggerVisualizer
          path: src/CurlDebuggerVisualizer/bin/Release/CurlDebuggerVisualizer.vsix
