name: Build
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build src/CurlDebuggerVisualizer/CurlDebuggerVisualizer.csproj -c Release
      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: CurlDebuggerVisualizer
          path: src/CurlDebuggerVisualizer/bin/Release/CurlDebuggerVisualizer.vsix
